In [42]:
import matplotlib as plt
import numpy as np
import pandas as pd

In [43]:
    
data = pd.read_excel('data.xlsx')
data_likes = data.as_matrix()

# data[left:right, bottom:top] data[delete columns, delete rows]

# Samples and Dimension

N, D = data_likes.shape

# To Text

data_likes[:, 1][data_likes[:, 1] == 0] = 'Sin mangas'
data_likes[:, 1][data_likes[:, 1] == 1] = 'Corta'
data_likes[:, 1][data_likes[:, 1] == 2] = 'Larga'

# get_ipython().magic('save previous_session ~1/') # 1 = Ipython
# get_ipython().magic('save current_session ~0/') # 2 = Python

data_likes[:, 2][data_likes[:, 2] == 0] = 'Polo'
data_likes[:, 2][data_likes[:, 2] == 1] = 'Scoop'
data_likes[:, 2][data_likes[:, 2] == 2] = 'V-Neck'

In [44]:
# Here come the LIKES

likes = np.zeros([N, 1]).T
# likes = np.array([1, 1, 0, 1, 0, 0, 0, 0, 0])

# likes = []

def getLikes():
    like = []
    for samples in range(0, N):
        print("Nombre de prenda", data_likes[samples, 0], "\n Caracteristicas: \n  1)Manga:", data_likes[samples, 1])
        print("  2)Cuello:", data_likes[samples, 2], "\n  3)Bolsillos:", data_likes[samples, 3], "\n  4)Botones:", data_likes[samples, 4])
        print("  5)Imagen:", data_likes[samples, 5])
        likes[:, samples] = int(input("¿Te gusta?. Si(1) | No(0) -> "))

In [82]:
likes

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [45]:
# Here Come the predictions

data_matrix = data.as_matrix()[:, 1:]

# 1) Normalize Columns


data_matrix[:, 0] = (data_matrix[:, 0] - data_matrix[:, 0].mean()) / data_matrix[:, 0].std()
data_matrix[:, 1] = (data_matrix[:, 1] - data_matrix[:, 1].mean()) / data_matrix[:, 1].std()


In [111]:
data_matrix

array([[0.15075567228888187, 0.5000000000000001, 0, 0, 1],
       [0.15075567228888187, 0.5000000000000001, 0, 0, 0],
       [1.507556722888818, -1.0, 0, 0, 0],
       [0.15075567228888187, 2.0000000000000004, 0, 0, 0],
       [1.507556722888818, -1.0, 1, 1, 0],
       [-1.2060453783110543, 0.5000000000000001, 0, 0, 1],
       [-1.2060453783110543, -1.0, 0, 0, 0],
       [0.15075567228888187, -1.0, 1, 0, 1],
       [-1.2060453783110543, 0.5000000000000001, 0, 1, 0]], dtype=object)

In [89]:
# 2) Stardard Varibles

def getStandardVariables():
    global X, Y, W, b
    X = data_matrix.astype(float)
    Y = likes.astype(float).T
    W = np.random.rand(D-1, 1)
    b = 0

In [91]:
getStandardVariables()

In [92]:
# 3) Define Train and Test

def getForwardVariables():
    global Xtrain, Ytrain, Xtest, Ytest
    Xtrain = X[:6, :]
    Ytrain = Y[:6]
    Xtest = X[-3:, :]
    Ytest = Y[-3:]
    print(Ytrain)

In [93]:
getForwardVariables()

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [86]:
Ytrain

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [49]:
# 4) Define forward functions

def sigmoid(x): # Sigmoid function to give a importance to the data
    return 1/(1+np.exp(-x))

def forward(w, x, b): # Do the prediction
    return sigmoid(x.dot(w)+ b)

In [50]:
# 6) Classification for seeing the results

def classification_rate(Y, P):
    return np.mean(Y == P)

In [71]:
# 5) Define predict function and costs

train_costs = []
test_costs = []

def predict_weight(w, x, b, learn_rate = 0.01, iterations=1000):
    global pYtrain, pYtest
    for i in range(iterations):
        pYtrain = forward(w, Xtrain, b)
        pYtest = forward(w, Xtest, b)

        ctrain = cross_entropy(Ytrain, pYtrain)
        ctest = cross_entropy(Ytest, pYtest)

        train_costs.append(ctrain)
        test_costs.append(ctest)
        
        gradientDescent(Xtrain, Ytrain, pYtrain, learn_rate);

        if(1 % 1000 == 0):
            print(i, ctrain, ctest)

    print("Final train Classification rate", classification_rate(Ytrain, np.round(pYtrain)))
    print("Final test classification rate", classification_rate(Ytest, np.round(pYtest)))

    

def gradientDescent(Xtrain, Ytrain, pYtrain, learn_rate):
    global W, b
    W -= learn_rate * Xtrain.dot((pYtrain - Ytrain).T)
    b -= learn_rate * (pYtrain - Ytrain).sum()
    



In [77]:
forward(W, Xtrain, b)

array([[ 0.679477  ],
       [ 0.61651287],
       [ 0.64941459],
       [ 0.81870366],
       [ 0.79452638],
       [ 0.39576548]])

In [112]:
pYtrain

array([[ 0.7346797 ],
       [ 0.62097463],
       [ 0.68439153],
       [ 0.82264887],
       [ 0.90811593],
       [ 0.42493311]])

In [113]:
Ytrain

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [75]:
Xtrain

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ]])

In [97]:
Xtrain

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ]])

In [110]:
(pYtrain - Ytrain).T

array([[ 0.7346797 ,  0.62097463,  0.68439153,  0.82264887,  0.90811593,
         0.42493311]])

In [109]:
Xtrain * np.array([1, 1, 1, 1, 1])

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ]])

In [95]:
predict_weight(W, Xtrain, b)

ValueError: shapes (6,5) and (1,6) not aligned: 5 (dim 1) != 1 (dim 0)

In [52]:
getLikes()

Nombre de prenda Deniseausti 
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Nyfifth  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Ilovecashmere  
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Walmart  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: V-Neck 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Tackroominc 
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 1 
  4)Botones: 1
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Shaina 
 Caracteristicas: 
  1)Manga: Sin mangas
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Test 
 Ca

In [53]:
getStandardVariables()

In [54]:
getForwardVariables()

In [55]:
W

array([[ 0.8656464 ],
       [ 0.68854407],
       [ 0.32490907],
       [ 0.41105245],
       [ 0.27659623]])

In [56]:
X

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ],
       [-1.20604538, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567, -1.        ,  1.        ,  0.        ,  1.        ],
       [-1.20604538,  0.5       ,  0.        ,  1.        ,  0.        ]])

In [57]:
predict_weight(W, X, b)

ValueError: shapes (6,5) and (9,6) not aligned: 5 (dim 1) != 9 (dim 0)

In [58]:

def gradientDescent(Xtrain, Ytrain, pYtrain, learn_rate):
    global W, b, test
    test = pYtrain
    W -= learn_rate * Xtrain.dot((pYtrain - Ytrain.T).T)
    b -= learn_rate * (pYtrain - Ytrain).sum()

    