In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn import linear_model

In [4]:
# Data

data = pd.read_excel('data.xlsx')
data_likes = data.as_matrix()
X = data_likes[:, 1:]
Y = np.array([[1, 1, 1, 0, 0, 0, 1, 1, 0]]).T
X

array([[1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [1, 2, 0, 0, 0],
       [2, 0, 1, 1, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=object)

In [5]:
# Train and Test DataSets

Xtrain = X[:7, :]
Ytrain = Y[:7, :]

Xtest = X[-2:]
Ytest = Y[-2:]
Xtest

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=object)

In [6]:
model = linear_model.LogisticRegression()

In [7]:
model.fit(Xtrain, Ytrain)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'ovr',
 'n_jobs': 1,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [9]:
model.predict(X)

array([1, 1, 1, 0, 0, 0, 1, 1, 0])

In [13]:
model.score(Xtrain, Ytrain)

1.0