In [1]:
import pandas as pd
import numpy as np

In [2]:
excel = pd.read_excel('./data.xlsx')

# Data Preprocessing

#### As a Matrix

In [3]:
data = excel.as_matrix()

##### X matrix processing (Normalize columns)

In [4]:
X = data[:, 1:]
X[:, 0] = (X[:, 0] - X[:, 0].mean()) / X[:, 0].std()
X[:, 1] = (X[:, 1] - X[:, 1].mean()) / X[:, 1].std()

#### X matrix as float type

In [5]:
X = X.astype(float)

#### Y matrix

In [6]:
Y = np.array([[1, 1, 0, 1, 0, 0, 0, 0, 0]]).T

In [7]:
# Only if we want to test.

# Weight and Dimensions

In [8]:
N, D = X.shape
W = np.random.randn(D, 1)
b = 0

# Forward Variables

In [9]:
# Train

Xtrain = X[:6, :]
Ytrain = Y[:6, :]

# Test

Xtest = X[6:, :]
Ytest = Y[6:, :]

# Prediction Function

In [10]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Forward Function

In [11]:
def forward(w, x, b): # Do the prediction
    return sigmoid(x.dot(w)+ b)

# Clasification Rate

In [12]:
def classification_rate(Y, P):
    return np.mean(Y == P)

# Cross Entropy

In [16]:
def cross_entropy(t, y): # Targets and predictions
    return t * np.log(y) + (1-t) * np.log(1-y)

# Final...

In [27]:
learn_rate = 0.01
iterations = 1000

train_costs = []
test_costs = []

for i in range(iterations):
    pYtrain = forward(W, Xtrain, b)
    pYtest = forward(W, Xtest, b)

    ctrain = cross_entropy(Ytrain, pYtrain)
    ctest = cross_entropy(Ytest, pYtest)

    train_costs.append(ctrain)
    test_costs.append(ctest)
        
    # Gradient Descent
    
    W -= learn_rate * Xtrain.T.dot(pYtrain - Ytrain)
    b -= learn_rate * (pYtrain - Ytrain).sum()

    if(1 % 1000 == 0):
        print(i, ctrain, ctest)

print("Final train Classification rate", classification_rate(Ytrain, np.round(pYtrain)))
print("Final test classification rate", classification_rate(Ytest, np.round(pYtest)))

Final train Classification rate 1.0
Final test classification rate 1.0


In [28]:
W

array([[ 2.73677242],
       [ 5.83932216],
       [-0.6779961 ],
       [-0.68119962],
       [-0.53990271]])

In [19]:
X

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ],
       [-1.20604538, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567, -1.        ,  1.        ,  0.        ,  1.        ],
       [-1.20604538,  0.5       ,  0.        ,  1.        ,  0.        ]])

In [20]:
data

array([['Deniseausti', 0.15075567228888187, 0.5000000000000001, 0, 0, 1],
       ['Nyfifth ', 0.15075567228888187, 0.5000000000000001, 0, 0, 0],
       ['Ilovecashmere ', 1.507556722888818, -1.0, 0, 0, 0],
       ['Walmart ', 0.15075567228888187, 2.0000000000000004, 0, 0, 0],
       ['Tackroominc', 1.507556722888818, -1.0, 1, 1, 0],
       ['Shaina', -1.2060453783110543, 0.5000000000000001, 0, 0, 1],
       ['Test', -1.2060453783110543, -1.0, 0, 0, 0],
       ['Test', 0.15075567228888187, -1.0, 1, 0, 1],
       ['Test', -1.2060453783110543, 0.5000000000000001, 0, 1, 0]], dtype=object)

In [21]:
X

array([[ 0.15075567,  0.5       ,  0.        ,  0.        ,  1.        ],
       [ 0.15075567,  0.5       ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567,  2.        ,  0.        ,  0.        ,  0.        ],
       [ 1.50755672, -1.        ,  1.        ,  1.        ,  0.        ],
       [-1.20604538,  0.5       ,  0.        ,  0.        ,  1.        ],
       [-1.20604538, -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15075567, -1.        ,  1.        ,  0.        ,  1.        ],
       [-1.20604538,  0.5       ,  0.        ,  1.        ,  0.        ]])

In [22]:
forward(W, X[:1, :], b)

array([[ 0.78839649]])

# Get Likes

In [23]:
data_likes = excel.as_matrix()

# data[left:right, bottom:top] data[delete columns, delete rows]

# Samples and Dimension

N, D = data_likes.shape

# To Text

data_likes[:, 1][data_likes[:, 1] == 0] = 'Sin mangas'
data_likes[:, 1][data_likes[:, 1] == 1] = 'Corta'
data_likes[:, 1][data_likes[:, 1] == 2] = 'Larga'

# get_ipython().magic('save previous_session ~1/') # 1 = Ipython
# get_ipython().magic('save current_session ~0/') # 2 = Python

data_likes[:, 2][data_likes[:, 2] == 0] = 'Polo'
data_likes[:, 2][data_likes[:, 2] == 1] = 'Scoop'
data_likes[:, 2][data_likes[:, 2] == 2] = 'V-Neck'

In [24]:
def getLikes():
    likes = []
    for samples in range(0, N):
        menu_options = True;
        while(menu_options):
            print("Nombre de prenda", data_likes[samples, 0], "\n Caracteristicas: \n  1)Manga:", data_likes[samples, 1])
            print("  2)Cuello:", data_likes[samples, 2], "\n  3)Bolsillos:", data_likes[samples, 3], "\n  4)Botones:", data_likes[samples, 4])
            print("  5)Imagen:", data_likes[samples, 5])
            like = float(input("¿Te gusta?. Si(1) | No(0) -> "))
            if(like == 0 or like == 1):
                menu_options = False
            else:
                print('Only numbers between 0 and 1.')
        likes.append(like)
    return likes

In [25]:
getLikes()

Nombre de prenda Deniseausti 
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Nyfifth  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Ilovecashmere  
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Walmart  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: V-Neck 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Tackroominc 
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 1 
  4)Botones: 1
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 1
Nombre de prenda Shaina 
 Caracteristicas: 
  1)Manga: Sin mangas
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 1
Nombre de prenda Test 
 Ca

[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0]

In [26]:
Y = np.array([getLikes()]).T

Nombre de prenda Deniseausti 
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Nyfifth  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Ilovecashmere  
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Walmart  
 Caracteristicas: 
  1)Manga: Corta
  2)Cuello: V-Neck 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 0
Nombre de prenda Tackroominc 
 Caracteristicas: 
  1)Manga: Larga
  2)Cuello: Polo 
  3)Bolsillos: 1 
  4)Botones: 1
  5)Imagen: 0
¿Te gusta?. Si(1) | No(0) -> 1
Nombre de prenda Shaina 
 Caracteristicas: 
  1)Manga: Sin mangas
  2)Cuello: Scoop 
  3)Bolsillos: 0 
  4)Botones: 0
  5)Imagen: 1
¿Te gusta?. Si(1) | No(0) -> 1
Nombre de prenda Test 
 Ca

In [30]:
forward(W, X[0, :], b)

array([ 0.79122952])